export const questions = [
  {
    id: 1,
    topic: "hadith",
    question: "What is the definition of hadith?",
    options: [
      "A collection of sayings and actions of Prophet Muhammad (PBUH)",
      "A collection of sayings of Prophet Muhammad (PBUH)",
      "A collection of actions of Prophet Muhammad (PBUH)",
      "A collection of sayings and actions of Prophet Eisa (PBUH)",
    ],
    answer: "A collection of sayings and actions of Prophet Muhammad (PBUH)",
    arabicTopic: "الحديث",
    arabic: "ما هو تعريف الحديث؟",
    arabicOptions: [
      "مجموعة من الكلمات والأعمال التي قالها النبي صلى الله عليه وسلم",
      "مجموعة من الكلمات التي قالها النبي صلى الله عليه وسلم",
      "مجموعة من الأعمال التي قالها النبي صلى الله عليه وسلم",
      "مجموعة من الكلمات والأعمال التي قالها النبي عيسى صلى الله عليه وسلم",
    ],
    arabicAnswer:
      "مجموعة من الكلمات والأعمال التي قالها النبي صلى الله عليه وسلم",
  },
  {
    id: 2,
    topic: "hadith",
    question:
      "Which book is considered the most authentic collection of hadith?",
    options: [
      "Sunan Abu Dawood",
      "Sahih al-Bukhari",
      "Sunan Ibn Majah",
      "Sahih Muslim",
    ],
    answer: "Sahih al-Bukhari",
    arabicTopic: "الحديث",
    arabic: "ما هو أصح كتاب في جمع الحديث؟",
    arabicOptions: [
      "سنن أبي داوود",
      "صحيح البخاري",
      "سنن ابن ماجه",
      "صحيح مسلم",
    ],
    arabicAnswer: "صحيح البخاري",
  },
  {
    id: 3,
    topic: "fiqh",
    question: "What is the meaning of Fiqh in Islam?",
    options: [
      "Memorizing the Quran",
      "Understanding Islamic rulings and laws",
      "Learning Arabic grammar",
      "Studying hadith",
    ],
    answer: "Understanding Islamic rulings and laws",
    arabicTopic: "الفقه",
    arabic: "ما معنى الفقه في الإسلام؟",
    arabicOptions: [
      "حفظ القرآن",
      "فهم الأحكام والقوانين الإسلامية",
      "تعلم قواعد اللغة العربية",
      "دراسة الحديث",
    ],
    arabicAnswer: "فهم الأحكام والقوانين الإسلامية",
  },
  {
    id: 4,
    topic: "quran",
    question: "How many surahs are there in the Quran?",
    options: ["113", "114", "115", "112"],
    answer: "114",
    arabicTopic: "القرآن",
    arabic: "كم عدد السور في القرآن الكريم؟",
    arabicOptions: ["١١٣", "١١٤", "١١٥", "١١٢"],
    arabicAnswer: "١١٤",
  },
  {
    id: 5,
    topic: "sahabah",
    question: "Who was the first person to accept Islam from the companions?",
    options: [
      "Umar ibn Al-Khattab",
      "Abu Bakr As-Siddiq",
      "Ali ibn Abi Talib",
      "Bilal ibn Rabah",
    ],
    answer: "Abu Bakr As-Siddiq",
    arabicTopic: "الصحابة",
    arabic: "من هو أول من أسلم من الصحابة؟",
    arabicOptions: [
      "عمر بن الخطاب",
      "أبو بكر الصديق",
      "علي بن أبي طالب",
      "بلال بن رباح",
    ],
    arabicAnswer: "أبو بكر الصديق",
  },
  {
    id: 6,
    topic: "fiqh",
    question: "How many daily prayers are obligatory in Islam?",
    options: ["Five", "Three", "Seven", "Two"],
    answer: "Five",
    arabicTopic: "الفقه",
    arabic: "كم عدد الصلوات المفروضة يومياً في الإسلام؟",
    arabicOptions: ["خمس", "ثلاث", "سبع", "اثنتان"],
    arabicAnswer: "خمس",
  },
];
